apiVersion: apps/v1
kind: Deployment
metadata:
  name: tworp
  labels:
    app: tworp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tworp
  template:
    metadata:
      labels:
        app: tworp
    spec:
      containers:
        - name: tworp
          image: weslleystein/tworp2
          env:
            - name: TWORPTEST
              valueFrom:
                secretKeyRef:
                  name: tworp
                  key: TWORPTEST
          ports:
            - containerPort: 80

